[general]
shuffle_caption = false
caption_extension = '.txt'
keep_tokens = 1

[[datasets]]
resolution = 1024
batch_size = 1
keep_tokens = 1

  [[datasets.subsets]]
  image_dir = '/home/user/three-gen-subnet-trellis/fluxgym/datasets/my-lora'
  class_tokens = '3dgen'
  num_repeats = 10