accelerate launch \
  --mixed_precision bf16 \
  --num_cpu_threads_per_process 1 \
  sd-scripts/flux_train_network.py \
  --pretrained_model_name_or_path "/home/user/three-gen-subnet-trellis/fluxgym/models/unet/flux1-schnell.safetensors" \
  --clip_l "/home/user/three-gen-subnet-trellis/fluxgym/models/clip/clip_l.safetensors" \
  --t5xxl "/home/user/three-gen-subnet-trellis/fluxgym/models/clip/t5xxl_fp16.safetensors" \
  --ae "/home/user/three-gen-subnet-trellis/fluxgym/models/vae/ae.sft" \
  --cache_latents_to_disk \
  --save_model_as safetensors \
  --sdpa --persistent_data_loader_workers \
  --max_data_loader_n_workers 2 \
  --seed 42 \
  --gradient_checkpointing \
  --mixed_precision bf16 \
  --save_precision bf16 \
  --network_module networks.lora_flux \
  --network_dim 4 \
  --optimizer_type adamw8bit \
  --learning_rate 1e-4 \
  --cache_text_encoder_outputs \
  --cache_text_encoder_outputs_to_disk \
  --fp8_base \
  --highvram \
  --max_train_epochs 20 \
  --save_every_n_epochs 4 \
  --dataset_config "/home/user/three-gen-subnet-trellis/fluxgym/outputs/my-lora/dataset.toml" \
  --output_dir "/home/user/three-gen-subnet-trellis/fluxgym/outputs/my-lora" \
  --output_name my-lora \
  --timestep_sampling shift \
  --discrete_flow_shift 3.1582 \
  --model_prediction_type raw \
  --guidance_scale 1.0 \
  --loss_type l2 \